start: exp

?exp: add_exp

?add_exp: mul_exp
    | add_exp "+" mul_exp    -> add
    | add_exp "-" mul_exp    -> sub

?mul_exp: pow_exp
    | mul_exp "*" pow_exp    -> mul

?pow_exp: unary_exp
    | unary_exp "^" pow_exp  -> pow

?unary_exp: log_exp
    | "-" pow_exp            -> neg
    | "(" exp ")"            -> parens
    | NUMBER                 -> number

?log_exp: "log" unary_exp "base" unary_exp -> log

%import common.NUMBER
%ignore " "
